### ISSUE TITLE
replace blcr with dmtcp 

### ISSUE THREAD

**Issue by JensTimmerman** [hpcugent/csub#2]
see http://mug.mvapich.cse.ohio-state.edu/static/media/mug/presentations/2014/cooperman.pdf
- verify all steps in csub with dmtcp equiuvalent
- mpi support can wait?

**Comment by stdweird** [comment]
on EL7, this might be an option too http://criu.org/Comparison_to_other_CR_projects (but no MPI support, so probably start with DMTCP)

**Comment by JensTimmerman** [comment]
some possible helpful links

https://github.com/opoplawski/gridengine_dmtcp
https://arc.liv.ac.uk/SGE/howto/dmtcp.html

**Comment by boegel** [comment]
fixed in #10
